/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.List;
/**
 *
 * @author Asus
 */
public class Student_Enrollment extends javax.swing.JFrame {
    
    
    private EnrollmentDAO enrollmentDao = new EnrollmentDAO();
    private StudentDAO studentDao = new StudentDAO();
    private CourseDAO courseDao = new CourseDAO();  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Student_Enrollment.class.getName());
    
    /**
     * Creates new form Student_Enrollment
     */
    public Student_Enrollment() {
        initComponents();
        this.setLocationRelativeTo(null); // Centers the window
        populateComboBoxes();
        viewActionPerformed(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        enroll = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cmbStudentName = new javax.swing.JComboBox<>();
        cmbCourseName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnrollment = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 50, 126));

        jLabel1.setFont(new java.awt.Font("Swis721 Ex BT", 1, 24)); // NOI18N
        jLabel1.setText("ENROLLMENT MANAGEMENT WINDOW");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(235, 246, 245));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        enroll.setText("ENROLL");
        enroll.addActionListener(this::enrollActionPerformed);

        delete.setText("DELETE ");
        delete.addActionListener(this::deleteActionPerformed);

        jButton4.setText("BACK");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        cmbStudentName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStudentName.addActionListener(this::cmbStudentNameActionPerformed);

        cmbCourseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCourseName.addActionListener(this::cmbCourseNameActionPerformed);

        jLabel2.setText("Select Student");

        jLabel3.setText("Select Course");

        view.setText("VIEW");
        view.addActionListener(this::viewActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStudentName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCourseName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(view)
                                    .addComponent(enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(delete))
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(cmbStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(cmbCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enroll)
                    .addComponent(delete))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(view))
                .addContainerGap())
        );

        tblEnrollment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnrollment);
        if (tblEnrollment.getColumnModel().getColumnCount() > 0) {
            tblEnrollment.getColumnModel().getColumn(0).setResizable(false);
            tblEnrollment.getColumnModel().getColumn(1).setResizable(false);
            tblEnrollment.getColumnModel().getColumn(2).setResizable(false);
            tblEnrollment.getColumnModel().getColumn(3).setResizable(false);
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Enrollment ID", "Student", "Course", "Date" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
        });

        txtSearch.addActionListener(this::txtSearchActionPerformed);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );

        jPanel2.add(jPanel3, "card2");

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void populateComboBoxes() {
   try {
            cmbStudentName.removeAllItems();
            cmbCourseName.removeAllItems();

            // Fetch students and add ID to the front!
            List<Student> students = studentDao.getAllStudents();
            for (Student s : students) {
                // IMPORTANT: This forces the dropdown to show "1 - Rey Christian Magbanua"
                String fullStudentName = s.getStudentId() + " - " + s.getFirstName() + " " + s.getLastName();
                cmbStudentName.addItem(fullStudentName);
            }

            // Fetch courses and add ID to the front!
            List<Course> courses = courseDao.getAllCourses();
            for (Course c : courses) {
                // IMPORTANT: This forces the dropdown to show "101 - Programming"
                String fullCourseName = c.getCourseId() + " - " + c.getCourseName();
                cmbCourseName.addItem(fullCourseName);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading combo box data: " + e.getMessage());
        }
}
    private void enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollActionPerformed
if(cmbStudentName.getSelectedItem() == null || cmbCourseName.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a student and a course.");
            return;
        }

        try {
            Enrollment newEnrollment = new Enrollment();
            
            // 1. Get the full text from the combo boxes
            String selectedStudent = cmbStudentName.getSelectedItem().toString();
            String selectedCourse = cmbCourseName.getSelectedItem().toString();
            
            // 2. Split the text at the " - " and grab ONLY the first part (the ID number)
            // .trim() removes any accidental spaces like "1 " so it perfectly becomes "1"
        String studentIdOnly = selectedStudent.split("-")[0].trim();
        String courseIdOnly = selectedCourse.split("-")[0].trim();
            
            // 3. Save only the IDs to the database!
            newEnrollment.setStudent_Id(studentIdOnly);
            newEnrollment.setCourse_Id(courseIdOnly);
            
            newEnrollment.setEnrollment_Date(LocalDate.now().toString());

            // Delegate to DAO
            enrollmentDao.addEnrollment(newEnrollment);
            
            JOptionPane.showMessageDialog(this, "Student Enrolled Successfully!");
            viewActionPerformed(null); // Refresh table
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error enrolling student: " + e.getMessage());
        }
    }//GEN-LAST:event_enrollActionPerformed
   
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Main Main = new Main();
      Main.setVisible(true);
       this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
int selectedRow = tblEnrollment.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an enrollment from the table to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this enrollment?", "Warning", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            int enrollmentId = (int) tblEnrollment.getValueAt(selectedRow, 0);
            
            // Delegate to DAO
            boolean isDeleted = enrollmentDao.deleteEnrollment(enrollmentId);
            
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Enrollment Deleted Successfully!");
                viewActionPerformed(null); // Refresh table
            } else {
                JOptionPane.showMessageDialog(this, "Enrollment ID not found in database.");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error deleting enrollment: " + e.getMessage()); 
        }
                                          
    }//GEN-LAST:event_deleteActionPerformed

    private void cmbStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStudentNameActionPerformed

    private void cmbCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseNameActionPerformed

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
       // 1. Get the text typed in the search bar
        String searchString = txtSearch.getText().trim();
        
        // 2. Get the option currently selected in the ComboBox
        String selectedCategory = jComboBox1.getSelectedItem().toString(); 
        
        // 3. Get your table's model (NOTE: Change 'tblcourse' to your actual table name if you are on a different screen!)
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblEnrollment.getModel(); 
        javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(model);
        tblEnrollment.setRowSorter(sorter); 

        // 4. Apply the filter based on the ComboBox selection
        if (searchString.isEmpty()) {
            sorter.setRowFilter(null); // If search is empty, show everything
        } else {
            // THE FIX: We tell the RowFilter exactly which column index to look at!
            // Column indexes start at 0 (0 = 1st column, 1 = 2nd column, etc.)
            
            switch (selectedCategory) {
                case "Course ID":
                    // Only searches Column 0
                    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + searchString, 0)); 
                    break;
                case "Course Name":
                    // Only searches Column 1
                    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + searchString, 1)); 
                    break;
                case "Description":
                    // Only searches Column 2
                    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + searchString, 2)); 
                    break;
                case "Credits":
                    // Only searches Column 3
                    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + searchString, 3)); 
                    break;
                default:
                    // If they select "All" (or anything else), search everywhere!
                    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + searchString)); 
                    break;
            }
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1KeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String searchString = txtSearch.getText().trim();
        String selectedCategory = jComboBox1.getSelectedItem().toString(); 
        
        EnrollmentDAO dao = new EnrollmentDAO();
        List<Enrollment> searchResults;

        if (searchString.isEmpty()) {
            searchResults = dao.getAllEnrollments(); 
        } else {
            searchResults = dao.searchEnrollmentsByCategory(selectedCategory, searchString);
        }

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblEnrollment.getModel();
        model.setRowCount(0); 

        for (Enrollment e : searchResults) {
            model.addRow(new Object[]{
                e.getEnrollment_Id(),
                e.getStudent_Id(), 
                e.getCourse_Id(),  
                e.getEnrollment_Date()
            });
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) tblEnrollment.getModel();
            model.setRowCount(0); // Clear existing table data

            model.setColumnIdentifiers(new String[]{"Enrollment ID", "Student", "Course", "Date"});

            // Delegate to DAO
            List<Enrollment> enrollments = enrollmentDao.getAllEnrollments();

            for (Enrollment e : enrollments) {
                Object[] row = {
                    e.getEnrollment_Id(),
                    e.getStudent_Id(), // MATCHED
                    e.getCourse_Id(),  // MATCHED
                    e.getEnrollment_Date()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading table data: " + e.getMessage());
        }
    }//GEN-LAST:event_viewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Student_Enrollment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCourseName;
    private javax.swing.JComboBox<String> cmbStudentName;
    private javax.swing.JButton delete;
    private javax.swing.JButton enroll;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnrollment;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}